# fly.toml app configuration file generated for api-hobot-app on 2023-11-09T17:39:20-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "api-hobot-app"
primary_region = "den"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
